//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiCZ.markWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="fxl", ConfigurationName="markWS.homeportPortType")]
    public interface homeportPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="fxl#homeport:ЗаказатьКоды", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(СтатусыКМСводноМассив))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(СписокПартий))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ApiCZ.markWS.РезультатОбработкиЗаказа ЗаказатьКоды(ApiCZ.markWS.Заказ Заказ);
        
        [System.ServiceModel.OperationContractAttribute(Action="fxl#homeport:ЗаказатьКоды", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<ApiCZ.markWS.РезультатОбработкиЗаказа> ЗаказатьКодыAsync(ApiCZ.markWS.Заказ Заказ);
        
        [System.ServiceModel.OperationContractAttribute(Action="fxl#homeport:ПолучитьКоды", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(СтатусыКМСводноМассив))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(СписокПартий))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ApiCZ.markWS.СписокКМ ПолучитьКоды(string ИдЗаказа);
        
        [System.ServiceModel.OperationContractAttribute(Action="fxl#homeport:ПолучитьКоды", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<ApiCZ.markWS.СписокКМ> ПолучитьКодыAsync(string ИдЗаказа);
        
        [System.ServiceModel.OperationContractAttribute(Action="fxl#homeport:ОтчетПоИспользованиюКМ", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(СтатусыКМСводноМассив))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(СписокПартий))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ApiCZ.markWS.РезультатОбработкиОтчетаКМ ОтчетПоИспользованиюКМ(ApiCZ.markWS.ОтчетКМ ОтчетКМ);
        
        [System.ServiceModel.OperationContractAttribute(Action="fxl#homeport:ОтчетПоИспользованиюКМ", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<ApiCZ.markWS.РезультатОбработкиОтчетаКМ> ОтчетПоИспользованиюКМAsync(ApiCZ.markWS.ОтчетКМ ОтчетКМ);
        
        [System.ServiceModel.OperationContractAttribute(Action="fxl#homeport:ВыгрузитьВБицерба", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(СтатусыКМСводноМассив))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(СписокПартий))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ApiCZ.markWS.РезультатВыполненияОперации ВыгрузитьВБицерба(string ИдЗаказа);
        
        [System.ServiceModel.OperationContractAttribute(Action="fxl#homeport:ВыгрузитьВБицерба", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<ApiCZ.markWS.РезультатВыполненияОперации> ВыгрузитьВБицербаAsync(string ИдЗаказа);
        
        [System.ServiceModel.OperationContractAttribute(Action="fxl#homeport:ПолучитьСтатусВводаВОборот", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(СтатусыКМСводноМассив))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(СписокПартий))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ApiCZ.markWS.СтатусВводаВОборот ПолучитьСтатусВводаВОборот(string ИдДокумента);
        
        [System.ServiceModel.OperationContractAttribute(Action="fxl#homeport:ПолучитьСтатусВводаВОборот", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<ApiCZ.markWS.СтатусВводаВОборот> ПолучитьСтатусВводаВОборотAsync(string ИдДокумента);
        
        [System.ServiceModel.OperationContractAttribute(Action="fxl#homeport:ПолучитьИнформациюПоКодам", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(СтатусыКМСводноМассив))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(СписокПартий))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string ПолучитьИнформациюПоКодам(ApiCZ.markWS.МассивКМ МассивКМ);
        
        [System.ServiceModel.OperationContractAttribute(Action="fxl#homeport:ПолучитьИнформациюПоКодам", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> ПолучитьИнформациюПоКодамAsync(ApiCZ.markWS.МассивКМ МассивКМ);
        
        [System.ServiceModel.OperationContractAttribute(Action="fxl#homeport:ПривязатьКМКПартии", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(СтатусыКМСводноМассив))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(СписокПартий))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ApiCZ.markWS.РезультатВыполненияОперации ПривязатьКМКПартии(ApiCZ.markWS.СписокПривязки СписокПривязки);
        
        [System.ServiceModel.OperationContractAttribute(Action="fxl#homeport:ПривязатьКМКПартии", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<ApiCZ.markWS.РезультатВыполненияОперации> ПривязатьКМКПартииAsync(ApiCZ.markWS.СписокПривязки СписокПривязки);
        
        [System.ServiceModel.OperationContractAttribute(Action="fxl#homeport:ПолучитьСтатусКМПоПартии", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(СтатусыКМСводноМассив))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(СписокПартий))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ApiCZ.markWS.СтатусыКМСводно ПолучитьСтатусКМПоПартии(string НомерПартии, string ИНН);
        
        [System.ServiceModel.OperationContractAttribute(Action="fxl#homeport:ПолучитьСтатусКМПоПартии", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<ApiCZ.markWS.СтатусыКМСводно> ПолучитьСтатусКМПоПартииAsync(string НомерПартии, string ИНН);
        
        [System.ServiceModel.OperationContractAttribute(Action="fxl#homeport:ПолучитьСтатусКМПоПартиям", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(СтатусыКМСводноМассив))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(СписокПартий))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ApiCZ.markWS.СтатусыКМСводно ПолучитьСтатусКМПоПартиям(string СписокПартий, string ИНН);
        
        [System.ServiceModel.OperationContractAttribute(Action="fxl#homeport:ПолучитьСтатусКМПоПартиям", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<ApiCZ.markWS.СтатусыКМСводно> ПолучитьСтатусКМПоПартиямAsync(string СписокПартий, string ИНН);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="fxl")]
    public partial class Заказ : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object[] itemsField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Организация", typeof(Организация), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("СтрокиЗаказа", typeof(СтрокаЗаказа), Order=0)]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="fxl")]
    public partial class Организация : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string иннField;
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string инн {
            get {
                return this.иннField;
            }
            set {
                this.иннField = value;
                this.RaisePropertyChanged("инн");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=1)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="fxl")]
    public partial class СтрокаСтатусыКМСводноМассив : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string статусField;
        
        private int количествоField;
        
        private string номерПартииField;
        
        /// <remarks/>
        public string Статус {
            get {
                return this.статусField;
            }
            set {
                this.статусField = value;
                this.RaisePropertyChanged("Статус");
            }
        }
        
        /// <remarks/>
        public int Количество {
            get {
                return this.количествоField;
            }
            set {
                this.количествоField = value;
                this.RaisePropertyChanged("Количество");
            }
        }
        
        /// <remarks/>
        public string НомерПартии {
            get {
                return this.номерПартииField;
            }
            set {
                this.номерПартииField = value;
                this.RaisePropertyChanged("НомерПартии");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="fxl")]
    public partial class СтатусыКМСводноМассив : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Комментарий", typeof(object), IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("СтрокиСтатуса", typeof(СтрокаСтатусыКМСводноМассив), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Успешно", typeof(bool), Order=0)]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="fxl")]
    public partial class СтрокаСтатусыКМСводно : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string статусField;
        
        private int количествоField;
        
        /// <remarks/>
        public string Статус {
            get {
                return this.статусField;
            }
            set {
                this.статусField = value;
                this.RaisePropertyChanged("Статус");
            }
        }
        
        /// <remarks/>
        public int Количество {
            get {
                return this.количествоField;
            }
            set {
                this.количествоField = value;
                this.RaisePropertyChanged("Количество");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="fxl")]
    public partial class СтатусыКМСводно : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Комментарий", typeof(object), IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("СтрокиСтатуса", typeof(СтрокаСтатусыКМСводно), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Успешно", typeof(bool), Order=0)]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="fxl")]
    public partial class СтатусВводаВОборот : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string статусField;
        
        private string комментарийField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Статус {
            get {
                return this.статусField;
            }
            set {
                this.статусField = value;
                this.RaisePropertyChanged("Статус");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Комментарий {
            get {
                return this.комментарийField;
            }
            set {
                this.комментарийField = value;
                this.RaisePropertyChanged("Комментарий");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="fxl")]
    public partial class СтрокаСпискаПривязки : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string кмField;
        
        private string номерПартииField;
        
        /// <remarks/>
        public string КМ {
            get {
                return this.кмField;
            }
            set {
                this.кмField = value;
                this.RaisePropertyChanged("КМ");
            }
        }
        
        /// <remarks/>
        public string НомерПартии {
            get {
                return this.номерПартииField;
            }
            set {
                this.номерПартииField = value;
                this.RaisePropertyChanged("НомерПартии");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="fxl")]
    public partial class СписокПривязки : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ИНН", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("СтрокаСписка", typeof(СтрокаСпискаПривязки), Order=0)]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="fxl")]
    public partial class СписокПартий : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Партии", Order=0)]
        public string[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="fxl")]
    public partial class РезультатОбработкиОтчетаКМ : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ИдДокумента", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("МассивОшибочныхКМ", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Описание", typeof(string), IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Ошибка", typeof(System.Nullable<bool>), Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName", Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
                this.RaisePropertyChanged("ItemsElementName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="fxl", IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("##any:")]
        Item,
        
        /// <remarks/>
        ИдДокумента,
        
        /// <remarks/>
        МассивОшибочныхКМ,
        
        /// <remarks/>
        Описание,
        
        /// <remarks/>
        Ошибка,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="fxl")]
    public partial class РезультатВыполненияОперации : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool выполненоField;
        
        private string комментарийField;
        
        private string счетчикField;
        
        /// <remarks/>
        public bool Выполнено {
            get {
                return this.выполненоField;
            }
            set {
                this.выполненоField = value;
                this.RaisePropertyChanged("Выполнено");
            }
        }
        
        /// <remarks/>
        public string Комментарий {
            get {
                return this.комментарийField;
            }
            set {
                this.комментарийField = value;
                this.RaisePropertyChanged("Комментарий");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string Счетчик {
            get {
                return this.счетчикField;
            }
            set {
                this.счетчикField = value;
                this.RaisePropertyChanged("Счетчик");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="fxl")]
    public partial class МассивКМ : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("КМ", Order=0)]
        public string[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="fxl")]
    public partial class СтрокаСтатусКМ : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string кмField;
        
        private bool использованField;
        
        private bool использованFieldSpecified;
        
        private bool списанField;
        
        private bool списанFieldSpecified;
        
        private System.DateTime датаПроизводстваField;
        
        private string тНВЭДField;
        
        private string номерВСДField;
        
        private System.DateTime срокГодностиField;
        
        private bool срокГодностиFieldSpecified;
        
        private string номерПартииField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string КМ {
            get {
                return this.кмField;
            }
            set {
                this.кмField = value;
                this.RaisePropertyChanged("КМ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool Использован {
            get {
                return this.использованField;
            }
            set {
                this.использованField = value;
                this.RaisePropertyChanged("Использован");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ИспользованSpecified {
            get {
                return this.использованFieldSpecified;
            }
            set {
                this.использованFieldSpecified = value;
                this.RaisePropertyChanged("ИспользованSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool Списан {
            get {
                return this.списанField;
            }
            set {
                this.списанField = value;
                this.RaisePropertyChanged("Списан");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool СписанSpecified {
            get {
                return this.списанFieldSpecified;
            }
            set {
                this.списанFieldSpecified = value;
                this.RaisePropertyChanged("СписанSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=3)]
        public System.DateTime ДатаПроизводства {
            get {
                return this.датаПроизводстваField;
            }
            set {
                this.датаПроизводстваField = value;
                this.RaisePropertyChanged("ДатаПроизводства");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ТНВЭД {
            get {
                return this.тНВЭДField;
            }
            set {
                this.тНВЭДField = value;
                this.RaisePropertyChanged("ТНВЭД");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string НомерВСД {
            get {
                return this.номерВСДField;
            }
            set {
                this.номерВСДField = value;
                this.RaisePropertyChanged("НомерВСД");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=6)]
        public System.DateTime СрокГодности {
            get {
                return this.срокГодностиField;
            }
            set {
                this.срокГодностиField = value;
                this.RaisePropertyChanged("СрокГодности");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool СрокГодностиSpecified {
            get {
                return this.срокГодностиFieldSpecified;
            }
            set {
                this.срокГодностиFieldSpecified = value;
                this.RaisePropertyChanged("СрокГодностиSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string НомерПартии {
            get {
                return this.номерПартииField;
            }
            set {
                this.номерПартииField = value;
                this.RaisePropertyChanged("НомерПартии");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="fxl")]
    public partial class ОтчетКМ : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object[] itemsField;
        
        private ItemsChoiceType1[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("НомерЛицензии", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("НомерСертификата", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Организация", typeof(Организация), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Ответственный", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Собственник", typeof(object), IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Строки", typeof(СтрокаСтатусКМ), Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName", Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType1[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
                this.RaisePropertyChanged("ItemsElementName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="fxl", IncludeInSchema=false)]
    public enum ItemsChoiceType1 {
        
        /// <remarks/>
        НомерЛицензии,
        
        /// <remarks/>
        НомерСертификата,
        
        /// <remarks/>
        Организация,
        
        /// <remarks/>
        Ответственный,
        
        /// <remarks/>
        Собственник,
        
        /// <remarks/>
        Строки,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="fxl")]
    public partial class КМ : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string кодField;
        
        private bool использованField;
        
        private string идЗаказаField;
        
        private string gtinField;
        
        private Организация организацияField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Код {
            get {
                return this.кодField;
            }
            set {
                this.кодField = value;
                this.RaisePropertyChanged("Код");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool Использован {
            get {
                return this.использованField;
            }
            set {
                this.использованField = value;
                this.RaisePropertyChanged("Использован");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ИдЗаказа {
            get {
                return this.идЗаказаField;
            }
            set {
                this.идЗаказаField = value;
                this.RaisePropertyChanged("ИдЗаказа");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string gtin {
            get {
                return this.gtinField;
            }
            set {
                this.gtinField = value;
                this.RaisePropertyChanged("gtin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public Организация Организация {
            get {
                return this.организацияField;
            }
            set {
                this.организацияField = value;
                this.RaisePropertyChanged("Организация");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="fxl")]
    public partial class СписокКМ : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("КМ", typeof(КМ), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Количество", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Комментарий", typeof(string), IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Ошибка", typeof(bool), Order=0)]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="fxl")]
    public partial class РезультатОбработкиЗаказа : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string идЗаказаЧЗField;
        
        private System.Nullable<int> ожидаемоеВремяВыполненияField;
        
        private bool ожидаемоеВремяВыполненияFieldSpecified;
        
        private System.Nullable<bool> ошибкаField;
        
        private bool ошибкаFieldSpecified;
        
        private string описаниеField;
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string ИдЗаказаЧЗ {
            get {
                return this.идЗаказаЧЗField;
            }
            set {
                this.идЗаказаЧЗField = value;
                this.RaisePropertyChanged("ИдЗаказаЧЗ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<int> ОжидаемоеВремяВыполнения {
            get {
                return this.ожидаемоеВремяВыполненияField;
            }
            set {
                this.ожидаемоеВремяВыполненияField = value;
                this.RaisePropertyChanged("ОжидаемоеВремяВыполнения");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ОжидаемоеВремяВыполненияSpecified {
            get {
                return this.ожидаемоеВремяВыполненияFieldSpecified;
            }
            set {
                this.ожидаемоеВремяВыполненияFieldSpecified = value;
                this.RaisePropertyChanged("ОжидаемоеВремяВыполненияSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<bool> Ошибка {
            get {
                return this.ошибкаField;
            }
            set {
                this.ошибкаField = value;
                this.RaisePropertyChanged("Ошибка");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ОшибкаSpecified {
            get {
                return this.ошибкаFieldSpecified;
            }
            set {
                this.ошибкаFieldSpecified = value;
                this.RaisePropertyChanged("ОшибкаSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string Описание {
            get {
                return this.описаниеField;
            }
            set {
                this.описаниеField = value;
                this.RaisePropertyChanged("Описание");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=4)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="fxl")]
    public partial class СтрокаЗаказа : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string gtinField;
        
        private int количествоField;
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string gtin {
            get {
                return this.gtinField;
            }
            set {
                this.gtinField = value;
                this.RaisePropertyChanged("gtin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Количество {
            get {
                return this.количествоField;
            }
            set {
                this.количествоField = value;
                this.RaisePropertyChanged("Количество");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=2)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface homeportPortTypeChannel : ApiCZ.markWS.homeportPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class homeportPortTypeClient : System.ServiceModel.ClientBase<ApiCZ.markWS.homeportPortType>, ApiCZ.markWS.homeportPortType {
        
        public homeportPortTypeClient() {
        }
        
        public homeportPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public homeportPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public homeportPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public homeportPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ApiCZ.markWS.РезультатОбработкиЗаказа ЗаказатьКоды(ApiCZ.markWS.Заказ Заказ) {
            return base.Channel.ЗаказатьКоды(Заказ);
        }
        
        public System.Threading.Tasks.Task<ApiCZ.markWS.РезультатОбработкиЗаказа> ЗаказатьКодыAsync(ApiCZ.markWS.Заказ Заказ) {
            return base.Channel.ЗаказатьКодыAsync(Заказ);
        }
        
        public ApiCZ.markWS.СписокКМ ПолучитьКоды(string ИдЗаказа) {
            return base.Channel.ПолучитьКоды(ИдЗаказа);
        }
        
        public System.Threading.Tasks.Task<ApiCZ.markWS.СписокКМ> ПолучитьКодыAsync(string ИдЗаказа) {
            return base.Channel.ПолучитьКодыAsync(ИдЗаказа);
        }
        
        public ApiCZ.markWS.РезультатОбработкиОтчетаКМ ОтчетПоИспользованиюКМ(ApiCZ.markWS.ОтчетКМ ОтчетКМ) {
            return base.Channel.ОтчетПоИспользованиюКМ(ОтчетКМ);
        }
        
        public System.Threading.Tasks.Task<ApiCZ.markWS.РезультатОбработкиОтчетаКМ> ОтчетПоИспользованиюКМAsync(ApiCZ.markWS.ОтчетКМ ОтчетКМ) {
            return base.Channel.ОтчетПоИспользованиюКМAsync(ОтчетКМ);
        }
        
        public ApiCZ.markWS.РезультатВыполненияОперации ВыгрузитьВБицерба(string ИдЗаказа) {
            return base.Channel.ВыгрузитьВБицерба(ИдЗаказа);
        }
        
        public System.Threading.Tasks.Task<ApiCZ.markWS.РезультатВыполненияОперации> ВыгрузитьВБицербаAsync(string ИдЗаказа) {
            return base.Channel.ВыгрузитьВБицербаAsync(ИдЗаказа);
        }
        
        public ApiCZ.markWS.СтатусВводаВОборот ПолучитьСтатусВводаВОборот(string ИдДокумента) {
            return base.Channel.ПолучитьСтатусВводаВОборот(ИдДокумента);
        }
        
        public System.Threading.Tasks.Task<ApiCZ.markWS.СтатусВводаВОборот> ПолучитьСтатусВводаВОборотAsync(string ИдДокумента) {
            return base.Channel.ПолучитьСтатусВводаВОборотAsync(ИдДокумента);
        }
        
        public string ПолучитьИнформациюПоКодам(ApiCZ.markWS.МассивКМ МассивКМ) {
            return base.Channel.ПолучитьИнформациюПоКодам(МассивКМ);
        }
        
        public System.Threading.Tasks.Task<string> ПолучитьИнформациюПоКодамAsync(ApiCZ.markWS.МассивКМ МассивКМ) {
            return base.Channel.ПолучитьИнформациюПоКодамAsync(МассивКМ);
        }
        
        public ApiCZ.markWS.РезультатВыполненияОперации ПривязатьКМКПартии(ApiCZ.markWS.СписокПривязки СписокПривязки) {
            return base.Channel.ПривязатьКМКПартии(СписокПривязки);
        }
        
        public System.Threading.Tasks.Task<ApiCZ.markWS.РезультатВыполненияОперации> ПривязатьКМКПартииAsync(ApiCZ.markWS.СписокПривязки СписокПривязки) {
            return base.Channel.ПривязатьКМКПартииAsync(СписокПривязки);
        }
        
        public ApiCZ.markWS.СтатусыКМСводно ПолучитьСтатусКМПоПартии(string НомерПартии, string ИНН) {
            return base.Channel.ПолучитьСтатусКМПоПартии(НомерПартии, ИНН);
        }
        
        public System.Threading.Tasks.Task<ApiCZ.markWS.СтатусыКМСводно> ПолучитьСтатусКМПоПартииAsync(string НомерПартии, string ИНН) {
            return base.Channel.ПолучитьСтатусКМПоПартииAsync(НомерПартии, ИНН);
        }
        
        public ApiCZ.markWS.СтатусыКМСводно ПолучитьСтатусКМПоПартиям(string СписокПартий, string ИНН) {
            return base.Channel.ПолучитьСтатусКМПоПартиям(СписокПартий, ИНН);
        }
        
        public System.Threading.Tasks.Task<ApiCZ.markWS.СтатусыКМСводно> ПолучитьСтатусКМПоПартиямAsync(string СписокПартий, string ИНН) {
            return base.Channel.ПолучитьСтатусКМПоПартиямAsync(СписокПартий, ИНН);
        }
    }
}
